/** Тексты сценария, новостей и пар имён — данные, без логики. */
export const NamePairs = Object.freeze({
  ru: [
    ['Велония', 'Дорстан'],
    ['Арния', 'Кратос'],
    ['Лурия', 'Тенбург'],
    ['Верен', 'Осталь'],
    ['Сарма', 'Квелт'],
    ['Морвен', 'Тагрум'],
    ['Эстарга', 'Брайхан'],
    ['Кальпен', 'Йоруа'],
    ['Норант', 'Сель'],
    ['Драверн', 'Корст'],
    ['Иктар', 'Полнат'],
    ['Аррея', 'Шёлндорф'],
    ['Велла', 'Зенгрод'],
    ['Каронт', 'Меграт'],
    ['Тильда', 'Орвент'],
  ],
  en: [
    ['Velonia', 'Dorstan'],
    ['Arnia', 'Kratos'],
    ['Luria', 'Tenburg'],
    ['Veren', 'Ostal'],
    ['Sarma', 'Kvelt'],
    ['Morven', 'Tagrum'],
    ['Estarga', 'Braihan'],
    ['Kalpen', 'Yorua'],
    ['Norant', 'Sel'],
    ['Dravern', 'Korst'],
    ['Iktar', 'Polnat'],
    ['Arrea', 'Scholndorf'],
    ['Vella', 'Zengrod'],
    ['Karont', 'Megrat'],
    ['Tilda', 'Orvent'],
  ],
});

export const CasusTemplates = {
  ru(A, B) {
    return [
      `Правительство ${A} заявляет, что этнические граждане ${A} в приграничных районах ${B} подвергаются систематическому преследованию. Ввиду отказа ${B} допустить наблюдателей ${A} объявляет о начале специальной операции.`,
      `После одностороннего провозглашения независимости северных провинций ${B} правительство ${B} исчерпало дипломатические возможности. Совет безопасности заблокирован. ${B} объявляет о восстановлении конституционного порядка силой.`,
      `Правительство ${A} заявило об обнаружении военных объектов ${B} у границы. Расценивая это как экзистенциальную угрозу, ${A} объявляет о превентивном ударе.`,
      `Вооружённые формирования, которых ${B} не признаёт, три месяца обстреливали приграничные сёла ${A}. После гибели мирных жителей ${A} объявляет войну.`,
      `Экономическая блокада, введённая ${B} два года назад, привела к кризису. Переговоры провалились. ${A} заявляет о прорыве блокады силой.`,
      `Тайные переговоры ${B} о вступлении в военный союз стали известны. ${A} квалифицирует это как нарушение нейтралитета и объявляет войну.`,
      `Историческая комиссия ${A} установила, что спорные земли всегда принадлежали народу ${A}. ${A} объявляет о возвращении исторических территорий.`,
      `Граждане ${A}, проживающие в ${B}, обратились за защитой. Парламент ${A} единогласно одобрил применение силы для защиты соотечественников.`,
      `${B} отказалось ратифицировать соглашение о реках, лишив ${A} доступа к питьевой воде. После трёх месяцев ультиматумов ${A} переходит к военным мерам.`,
      `Захват рыболовецкого судна ${A} в нейтральных водах был расценён как акт агрессии. ${A} начинает ответную операцию.`,
      `Покушение на посла ${A} в столице ${B} осталось без должного расследования. ${A} объявляет это объявлением войны де-факто.`,
      `Беспилотник ${B} был сбит над территорией ${A}. Анализ обломков подтвердил военное назначение. ${A} объявляет о начале возмездия.`,
      `Энергетическая инфраструктура ${A} подверглась кибератаке. Цифровой след ведёт к спецслужбам ${B}. ${A} переходит к военному ответу.`,
      `Президент ${A} ссылается на пакт о взаимной помощи: союзник просит вмешаться в конфликт против ${B}. ${A} вступает в войну.`,
      `Религиозные святыни народа ${A} на территории ${B} были осквернены. ${A} объявляет священную войну для их защиты.`,
      `${B} разместило ракетные комплексы в ста километрах от столицы ${A}. ${A} расценивает это как угрозу национальному выживанию.`,
      `Президент ${B} в публичном выступлении назвал ${A} «искусственным образованием». ${A} объявляет ответ оружием.`,
      `Документы, опубликованные службой разведки ${A}, доказывают подготовку ${B} к вторжению. ${A} наносит превентивный удар.`,
      `Контрабандистский маршрут ${B} разрушил экономику пограничных регионов ${A}. После провала переговоров ${A} закрывает границу силой.`,
      `Внеочередная сессия парламента ${A} утвердила пакет военных мер «для восстановления исторической справедливости» в отношении ${B}.`,
    ];
  },
  en(A, B) {
    return [
      `The government of ${A} states that its ethnic citizens in the border regions of ${B} face systematic persecution. Because ${B} refuses to admit observers, ${A} announces a special operation.`,
      `Following the unilateral declaration of independence by the northern provinces of ${B}, the Security Council is deadlocked. ${B} declares that it will restore constitutional order by force.`,
      `The government of ${A} has identified military installations belonging to ${B} near the border and announces a pre-emptive strike.`,
      `For three months, armed formations that ${B} refuses to acknowledge have shelled villages along the border of ${A}. After the death of civilians, ${A} declares war.`,
      `The blockade imposed by ${B} two years ago has triggered a humanitarian crisis. Mediation has failed. ${A} announces that it will break the blockade by force.`,
      `Secret negotiations in which ${B} sought to join a military alliance have become public. ${A} classifies this as a breach of neutrality and announces military operations.`,
      `The historical commission of ${A} has determined that the disputed lands have always belonged to the people of ${A}. ${A} announces the recovery of its historical territories.`,
      `Citizens of ${A} residing in ${B} have appealed for protection. The parliament of ${A} has unanimously authorized force to defend its compatriots.`,
      `${B} refused to ratify the river-sharing agreement, depriving ${A} of drinking water. After three months of ultimatums, ${A} moves to military measures.`,
      `The seizure of an ${A} fishing vessel in neutral waters has been classified as an act of aggression. ${A} launches a retaliatory operation.`,
      `The assassination of the ${A} ambassador in the capital of ${B} remains uninvestigated. ${A} declares this a de facto declaration of war.`,
      `A ${B} drone was shot down over the territory of ${A}. Analysis of the debris confirmed its military purpose. ${A} initiates retaliation.`,
      `The energy infrastructure of ${A} has been struck by a cyberattack. The digital trail leads to intelligence services of ${B}. ${A} moves to a military response.`,
      `The president of ${A} invokes the mutual defence pact: an ally has requested intervention against ${B}. ${A} enters the war.`,
      `The religious shrines of the people of ${A}, located in ${B}, have been desecrated. ${A} declares a holy war for their defence.`,
      `${B} has deployed missile systems within a hundred kilometres of the capital of ${A}. ${A} considers this a threat to national survival.`,
      `In a public address, the president of ${B} called ${A} an "artificial entity". ${A} responds by force of arms.`,
      `Documents released by the intelligence service of ${A} prove preparations by ${B} for an invasion. ${A} delivers a pre-emptive strike.`,
      `Smuggling routes operating from ${B} have destroyed the economy of border regions of ${A}. After failed negotiations, ${A} closes the border by force.`,
      `An emergency session of the parliament of ${A} has approved a package of military measures "to restore historical justice" against ${B}.`,
    ];
  },
};

export const MicroStories = Object.freeze({
  ru: [
    'Продала обручальное кольцо, чтобы купить билет на самолёт',
    'Они ждали визу. Не получили',
    'Эмиграция — это маленькая смерть',
    'Родина там, где тебя зарыли в землю',
    'Не успел проститься с дочерью',
    'Едва исполнилось восемнадцать',
    'Четверо детей без отца',
    'Обещали, что всё кончится к зиме',
    'Старики не покидают своих домов',
    'Первый день на фронте',
    'Имя не значится в списках',
    'Место захоронения неизвестно',
    'Приказ пришёл ночью',
    'Дом стоит. Хозяина нет',
    'Форма вернулась. Он — нет',
    'Брат вернулся. Всегда молчит',
    'В кармане осталась кукла',
    'Вино кислое, как эта война',
    'Выжил, но перестал разговаривать',
    'Скрипка сгорела вместе с домом',
    'Слишком много наград для мертвеца',
    'В госпитале пахло безнадёгой и йодом',
    'Надела свадебное платье на его похороны',
    'Сапоги отдали молодому новобранцу',
    'Осколок застрял слишком близко к сердцу',
    'Собака ждала его у ворот три года',
    'Снег покрыл всё',
    'Он хотел стать врачом, а не убийцей',
    'У него были чистые глаза и грязная винтовка',
    'Страх пахнет сталью и мокрой землей',
    'Выпьем за тех, кто не дожил до утра',
    'Хранила его рубашку нестираной',
    'Она больше не могла плакать',
    'Убил человека, который был похож на брата',
    'Дождь смыл кровь',
    'Седина в двадцать лет это нормально',
    'Стал ненавидеть салюты',
    'Кофе дрянной, как и этот приказ',
    'Писала ему каждый день год после его смерти',
    'Мечтал о море в окопе',
    'Никто не спросил, хочет ли умирать',
    'Вина выжившего — самая тяжёлая ноша',
    'Смеялись перед тем, как начался обстрел',
    'Город восстановили, людей — нет',
    'Не допела колыбельную до конца',
    'Звала маму, но та молчала',
    'Любимый мишка остался лежать на земле',
    'Пятна на асфальте того же цвета, что и её бант',
    'Прижимала куклу, как будто та могла её спасти',
    'Письмо пришло через месяц после похорон',
    'Фотография в нагрудном кармане пробита навылет',
    'Дед отказался бросать корову',
    'Строил этот дом пятьдесят лет. Хватило одной мины',
    'Искала очки в пепле спальни. Не нашла',
    'Помню прошлую войну. Эта хуже',
    'Старая яблоня сгорела первой',
    'Молитва не остановила танк',
    'Похоронил внуков в саду',
    'У смерти нет выходных',
    'Был хорошим сапожником. Стал плохим солдатом',
    'Выстрелил первым. Придется с этим жить',
    'Газета сообщила о «незначительных потерях». Был в их числе',
    'Его собака выла три ночи подряд',
    'Нас списали в штабе еще вчера утром',
    'Мы в окружении',
    'Снег стал красным и быстро замерз',
    'Никто не хотел умирать',
    'Братья по общей могиле',
    'Танки шли лениво, как сытые звери',
    'Нас просто забыли здесь',
    'Больше нечем стрелять'
  ],
  en: [
    'Now he knows "please" in five languages',
    'A foreign sky is colder on a sunny day',
    'A passport is more valuable than a life',
    'She sold her wedding ring to buy a plane ticket',
    'Philosophy professor, became a night watchman at the port',
    'The children speak a different language now',
    'They waited for a visa. Didn\'t get it',
    'Emigration is a little death',
    'Foreign cities are beautiful until you have to survive in them',
    'Better to work as a dishwasher',
    'An immigrant\'s accent sounds like a man with no future',
    'Too old for a new life. Too young to die at home',
    'Homeland is where they bury you',
    'Didn\'t have time to say goodbye to his daughter',
    'Barely turned eighteen',
    'Four children without a father',
    'When the soldiers came, it smelled of bread and the sun shone brightly',
    'They promised it would be over by winter',
    'Old people don\'t leave their homes',
    'First day at the front',
    'His name isn\'t on the lists',
    'Burial place unknown',
    'The order came at night',
    'He was twenty-three',
    'The house stands. The owner does not',
    'The uniform returned. He did not',
    'His brother returned. He\'s always silent',
    'A doll was left in his pocket',
    'The wine is as sour as this war',
    'Survived, but stopped speaking',
    'The garden grew wild',
    'The violin burned with the house',
    'Too many medals for a dead man',
    'It smelled of apples and gunpowder',
    'The hospital smelled of despair and iodine',
    'She wore her wedding dress to his funeral',
    'His boots were given to a young recruit',
    'His hands shook at the sight of matches',
    'They weren\'t enemies until they were given rifles',
    'The shrapnel lodged too close to the heart',
    'The dog waited for him at the gate for three years',
    'Only a photograph with a torn corner remained',
    'Snow covered everything',
    'He wanted to be a doctor, not a killer',
    'He had clear eyes and a dirty rifle',
    'Fear smells of steel and wet earth',
    'Let\'s drink to those who didn\'t live to see the morning',
    'Keeps his shirt unwashed',
    'She didn\'t cry anymore',
    'Killed a man who looked like his brother',
    'The rain washed away the blood',
    'Gray hair at twenty',
    'They promised to be back for dinner',
    'Too many empty chairs',
    'Grew to hate fireworks',
    'Didn\'t recognize his wife in the crowd',
    'The coffee is as lousy as this order',
    'Wrote to him every day for a year after his death',
    'An empty cot in the barracks quickly finds a new owner',
    'Dreamed of the sea in a trench',
    'Nothing left but a canteen',
    'No one asked if he wanted to die',
    'His younger brother took his bed',
    'Survivor\'s guilt is the heaviest burden',
    'They were laughing before the shelling started',
    'The city was rebuilt, the people were not',
    'Didn\'t finish singing the lullaby',
    'She was calling for mom',
    'Her favorite teddy bear was left lying on the ground',
    'The stains on the asphalt were the same color as her bow',
    'She clutched the doll as if it could save her',
    'They were going to get married this Sunday',
    'A kiss tasting of gunpowder and tears',
    'She stopped looking in the mirror',
    'The letter arrived a month after the funeral',
    'The photograph in the breast pocket was shot straight through',
    'The old man refused to abandon his cow',
    'Built this house for fifty years. One minute was enough',
    'She looked for her glasses in the ashes of the bedroom. Didn\'t find them',
    'I remember the last war. This one is worse',
    'The old apple tree burned first',
    'A prayer didn\'t stop the tank',
    'Buried his grandchildren in the garden',
    'Returned, but couldn\'t find his street',
    'Death has no days off',
    'He was a good cobbler. Became a bad soldier',
    'Shot first. Will have to live with that',
    'The newspaper reported "minor casualties". He was among them',
    'The mud in the trench is warmer than a blanket',
    'Breakfast for one. Again',
    'The sun shone as if nothing had happened',
    'His dog howled for three nights straight',
    'The price of victory is an empty village',
    'HQ wrote us off yesterday morning',
    'Out of water. The well is on their side of the street',
    'We\'re surrounded',
    'Cleaned his rifle so carefully, as if he intended to live forever',
    'The snow turned red and quickly froze',
    'No one wanted to die',
    'Wrote a note. Read it after the battle',
    'Brothers by mass grave',
    'Asked what time it is. The stupidest question when surrounded',
    'The tanks moved lazily, like well-fed beasts',
    'Hunger stopped tormenting him',
    'We sat in the mud waiting for the offensive',
    'At least he didn\'t have to shine his boots anymore',
    'They just forgot about us here',
    'The lieutenant sat on the ground',
    'According to the map, there should be a forest here. Only stumps and corpses',
    'Nothing left to shoot with'
  ],
});

export const NewsLines = Object.freeze({
  ru: [
    'Рынок разрушен. Торговля прекращена.',
    'Урожай не убран. Зернохранилища пусты.',
    'Беженцы достигли побережья. Корабли не принимают.',
    'Госпиталь переполнен. Медикаменты на исходе.',
    'Школы закрыты третью неделю подряд.',
    'Послы отозваны. Переговоры не ведутся.',
    'Мост взорван. Деревня отрезана.',
    'Цены на хлеб выросли втрое.',
    'Комендантский час продлён до рассвета.',
    'Список пропавших — тысяча имён.',
    'Сводка потерь засекречена.',
    'Электростанция в руинах. Город без света.',
    'Поезда не ходят. Вокзалы пусты.',
    'Религиозные службы запрещены до особого распоряжения.',
    'Резервистов призывают пятый раз за месяц.',
    'Гуманитарный конвой остановлен на границе.',
    'Очереди за водой растягиваются на километры.',
    'Городское кладбище расширено в третий раз за год.',
    'Журналисты не возвращаются с фронта.',
    'Полевая почта работает с перебоями.',
    'Запрещён выезд для мужчин от восемнадцати до шестидесяти.',
    'Цены на лекарства пересмотрены. Многим уже всё равно.',
    'Радио передаёт только военные сводки.',
    'Парламент одобрил очередной военный бюджет.',
    'Президент обращается к нации в десятый раз за неделю.',
  ],
  en: [
    'Market destroyed. Trade halted.',
    'The harvest still stands in the fields. Granaries are empty.',
    'Refugees have reached the coast. No ship will take them.',
    'The hospital is overwhelmed. Medical supplies are running out.',
    'Schools have been closed for three weeks straight.',
    'Ambassadors recalled. Talks suspended.',
    'The bridge has been blown. The village is cut off.',
    'Bread prices have tripled.',
    'Curfew extended until dawn.',
    'Missing persons list: a thousand names.',
    'The casualty report has been classified.',
    'The power plant is in ruins. The city is dark.',
    'Trains have stopped running. The stations stand empty.',
    'Religious services suspended until further notice.',
    'Reservists are being called up for the fifth time this month.',
    'A humanitarian convoy has been halted at the border.',
    'Queues for water stretch for kilometres.',
    'The municipal cemetery has been expanded for the third time this year.',
    'Journalists no longer return from the front.',
    'Field mail is operating intermittently.',
    'Travel banned for men aged eighteen to sixty.',
    'Medicine prices revised. To many, it no longer matters.',
    'Radio broadcasts only military bulletins.',
    'Parliament has approved yet another military budget.',
    'The president has addressed the nation ten times this week.',
  ],
});

export const EndQuotes = Object.freeze({
  ru: [
    'Победитель в войне — это тот, кто меньше потерял. Но и он потерял.',
    'Солдаты умирают за то, что политики не могут решить за столом переговоров.',
    'Пограничный камень остался на том же месте.',
    'Причина войны всегда кажется ничтожной на фоне её последствий.',
    'Те, кто объявил войну, пережили её.',
    'Через десять лет здесь построят мемориал. Потом снесут при следующей войне.',
    'Историю напишут победители. Имена погибших — никто.',
    'Каждый километр имеет имя. Имя того, кто за него умер.',
    'Война заканчивается, когда нет уже даже того, за что её начали.',
    'Дети, родившиеся в этой войне, не помнят, как пахнет хлеб.',
    'Карты перерисуют. Шрамы — нет.',
    'Победа — это слово, которое произносят живые. Мёртвые молчат.',
    'Тот, кто пишет учебники истории, никогда не носил оружия.',
    'Самая длинная война — та, которая идёт в голове выжившего.',
    'Граница — это линия, которую кто-то однажды решил защищать жизнями других.',
  ],
  en: [
    'The victor in war is the one who lost less. But they still lost.',
    'Soldiers die for what politicians could not settle across a negotiating table.',
    'The border stone did not move.',
    'The cause of a war always seems trivial compared to its consequences.',
    'Those who declared the war outlived it.',
    'In ten years they will build a memorial here—then tear it down when the next war comes.',
    'History is written by the victors. The names of the dead, by no one.',
    'Every kilometre has a name. The name of the one who died for it.',
    'A war ends when there is nothing left even of what it began over.',
    'Children born in this war do not remember the smell of bread.',
    'Maps will be redrawn. Scars will not.',
    'Victory is a word spoken by the living. The dead are silent.',
    'Those who write the history books never carried a rifle.',
    'The longest war is the one in the head of the survivor.',
    'A border is a line someone once decided to defend with other people\'s lives.',
  ],
});

/** Пороги суммарных потерь для всплывающих сообщений */
export const CasualtyThresholds = Object.freeze({
  ru: {
    100000: 'Это больше, чем население среднего города.',
    500000: 'Полмиллиона. Столько зрителей вмещает двадцать стадионов.',
    1000000: 'Миллион. Некоторые войны в истории унесли меньше.',
  },
  en: {
    100000: 'More than the population of a mid-sized city.',
    500000: 'Half a million. That many people could fill twenty football stadiums.',
    1000000: 'One million dead. Some wars in history claimed fewer lives.',
  },
});
