/** Тексты сценария, новостей и пар имён — данные, без логики. */
export const NamePairs = Object.freeze({
  ru: [
    ['Велония', 'Дорстан'],
    ['Арния', 'Кратос'],
    ['Лурия', 'Тенбург'],
    ['Верен', 'Осталь'],
    ['Сарма', 'Квелт'],
  ],
  en: [
    ['Velonia', 'Dorstan'],
    ['Arnia', 'Kratos'],
    ['Luria', 'Tenburg'],
    ['Veren', 'Ostal'],
    ['Sarma', 'Kvelt'],
  ],
});

export const CasusTemplates = {
  ru(A, B) {
    return [
      `Правительство ${A} заявляет, что этнические граждане ${A} в приграничных районах ${B} подвергаются систематическому преследованию. Ввиду отказа ${B} допустить наблюдателей ${A} объявляет о начале специальной операции.`,
      `После одностороннего провозглашения независимости северных провинций ${B} правительство ${B} исчерпало дипломатические возможности. Совет безопасности заблокирован. ${B} объявляет о восстановлении конституционного порядка силой.`,
      `Правительство ${A} заявило об обнаружении военных объектов ${B} у границы. Расценивая это как экзистенциальную угрозу, ${A} объявляет о превентивном ударе.`,
      `Вооружённые формирования, которых ${B} не признаёт, три месяца обстреливали приграничные сёла ${A}. После гибели мирных жителей ${A} объявляет войну.`,
      `Экономическая блокада, введённая ${B} два года назад, привела к кризису. Переговоры провалились. ${A} заявляет о прорыве блокады силой.`,
      `Тайные переговоры ${B} о вступлении в военный союз стали известны. ${A} квалифицирует это как нарушение нейтралитета и объявляет войну.`,
    ];
  },
  en(A, B) {
    return [
      `The government of ${A} states that its ethnic citizens in the border regions of ${B} face systematic persecution. Because ${B} refuses to admit observers, ${A} announces a special operation.`,
      `Following the unilateral declaration of independence by the northern provinces of ${B}, the Security Council is deadlocked. ${B} declares that it will restore constitutional order by force.`,
      `The government of ${A} has identified military installations belonging to ${B} near the border and announces a pre-emptive strike.`,
      `For three months, armed formations that ${B} refuses to acknowledge have shelled villages along the border of ${A}. After the death of civilians, ${A} declares war.`,
      `The blockade imposed by ${B} two years ago has triggered a humanitarian crisis. Mediation has failed. ${A} announces that it will break the blockade by force.`,
      `Secret negotiations in which ${B} sought to join a military alliance have become public. ${A} classifies this as a breach of neutrality and announces military operations.`,
    ];
  },
};

export const MicroStories = Object.freeze({
  ru: [
    'Продала обручальное кольцо, чтобы купить билет на самолёт',
    'Они ждали визу. Не получили',
    'Эмиграция — это маленькая смерть',
    'Родина там, где тебя зарыли в землю',
    'Не успел проститься с дочерью',
    'Едва исполнилось восемнадцать',
    'Четверо детей без отца',
    'Обещали, что всё кончится к зиме',
    'Старики не покидают своих домов',
    'Первый день на фронте',
    'Имя не значится в списках',
    'Место захоронения неизвестно',
    'Приказ пришёл ночью',
    'Дом стоит. Хозяина нет',
    'Форма вернулась. Он — нет',
    'Брат вернулся. Всегда молчит',
    'В кармане осталась кукла',
    'Вино кислое, как эта война',
    'Выжил, но перестал разговаривать',
    'Скрипка сгорела вместе с домом',
    'Слишком много наград для мертвеца',
    'В госпитале пахло безнадёгой и йодом',
    'Надела свадебное платье на его похороны',
    'Сапоги отдали молодому новобранцу',
    'Осколок застрял слишком близко к сердцу',
    'Собака ждала его у ворот три года',
    'Снег покрыл всё',
    'Он хотел стать врачом, а не убийцей',
    'У него были чистые глаза и грязная винтовка',
    'Страх пахнет сталью и мокрой землей',
    'Выпьем за тех, кто не дожил до утра',
    'Хранила его рубашку нестираной',
    'Она больше не могла плакать',
    'Убил человека, который был похож на брата',
    'Дождь смыл кровь',
    'Седина в двадцать лет это нормально',
    'Стал ненавидеть салюты',
    'Кофе дрянной, как и этот приказ',
    'Писала ему каждый день год после его смерти',
    'Мечтал о море в окопе',
    'Никто не спросил, хочет ли умирать',
    'Вина выжившего — самая тяжёлая ноша',
    'Смеялись перед тем, как начался обстрел',
    'Город восстановили, людей — нет',
    'Не допела колыбельную до конца',
    'Звала маму, но та молчала',
    'Любимый мишка остался лежать на земле',
    'Пятна на асфальте того же цвета, что и её бант',
    'Прижимала куклу, как будто та могла её спасти',
    'Письмо пришло через месяц после похорон',
    'Фотография в нагрудном кармане пробита навылет',
    'Дед отказался бросать корову',
    'Строил этот дом пятьдесят лет. Хватило одной мины',
    'Искала очки в пепле спальни. Не нашла',
    'Помню прошлую войну. Эта хуже',
    'Старая яблоня сгорела первой',
    'Молитва не остановила танк',
    'Похоронил внуков в саду',
    'У смерти нет выходных',
    'Был хорошим сапожником. Стал плохим солдатом',
    'Выстрелил первым. Придется с этим жить',
    'Газета сообщила о «незначительных потерях». Был в их числе',
    'Его собака выла три ночи подряд',
    'Нас списали в штабе еще вчера утром',
    'Мы в окружении',
    'Снег стал красным и быстро замерз',
    'Никто не хотел умирать',
    'Братья по общей могиле',
    'Танки шли лениво, как сытые звери',
    'Нас просто забыли здесь',
    'Больше нечем стрелять'
  ],
  en: [
    'Now he knows "please" in five languages',
    'A foreign sky is colder on a sunny day',
    'A passport is more valuable than a life',
    'She sold her wedding ring to buy a plane ticket',
    'Philosophy professor, became a night watchman at the port',
    'The children speak a different language now',
    'They waited for a visa. Didn\'t get it',
    'Emigration is a little death',
    'Foreign cities are beautiful until you have to survive in them',
    'Better to work as a dishwasher',
    'An immigrant\'s accent sounds like a man with no future',
    'Too old for a new life. Too young to die at home',
    'Homeland is where they bury you',
    'Didn\'t have time to say goodbye to his daughter',
    'Barely turned eighteen',
    'Four children without a father',
    'When the soldiers came, it smelled of bread and the sun shone brightly',
    'They promised it would be over by winter',
    'Old people don\'t leave their homes',
    'First day at the front',
    'His name isn\'t on the lists',
    'Burial place unknown',
    'The order came at night',
    'He was twenty-three',
    'The house stands. The owner does not',
    'The uniform returned. He did not',
    'His brother returned. He\'s always silent',
    'A doll was left in his pocket',
    'The wine is as sour as this war',
    'Survived, but stopped speaking',
    'The garden grew wild',
    'The violin burned with the house',
    'Too many medals for a dead man',
    'It smelled of apples and gunpowder',
    'The hospital smelled of despair and iodine',
    'She wore her wedding dress to his funeral',
    'His boots were given to a young recruit',
    'His hands shook at the sight of matches',
    'They weren\'t enemies until they were given rifles',
    'The shrapnel lodged too close to the heart',
    'The dog waited for him at the gate for three years',
    'Only a photograph with a torn corner remained',
    'Snow covered everything',
    'He wanted to be a doctor, not a killer',
    'He had clear eyes and a dirty rifle',
    'Fear smells of steel and wet earth',
    'Let\'s drink to those who didn\'t live to see the morning',
    'Keeps his shirt unwashed',
    'She didn\'t cry anymore',
    'Killed a man who looked like his brother',
    'The rain washed away the blood',
    'Gray hair at twenty',
    'They promised to be back for dinner',
    'Too many empty chairs',
    'Grew to hate fireworks',
    'Didn\'t recognize his wife in the crowd',
    'The coffee is as lousy as this order',
    'Wrote to him every day for a year after his death',
    'An empty cot in the barracks quickly finds a new owner',
    'Dreamed of the sea in a trench',
    'Nothing left but a canteen',
    'No one asked if he wanted to die',
    'His younger brother took his bed',
    'Survivor\'s guilt is the heaviest burden',
    'They were laughing before the shelling started',
    'The city was rebuilt, the people were not',
    'Didn\'t finish singing the lullaby',
    'She was calling for mom',
    'Her favorite teddy bear was left lying on the ground',
    'The stains on the asphalt were the same color as her bow',
    'She clutched the doll as if it could save her',
    'They were going to get married this Sunday',
    'A kiss tasting of gunpowder and tears',
    'She stopped looking in the mirror',
    'The letter arrived a month after the funeral',
    'The photograph in the breast pocket was shot straight through',
    'The old man refused to abandon his cow',
    'Built this house for fifty years. One minute was enough',
    'She looked for her glasses in the ashes of the bedroom. Didn\'t find them',
    'I remember the last war. This one is worse',
    'The old apple tree burned first',
    'A prayer didn\'t stop the tank',
    'Buried his grandchildren in the garden',
    'Returned, but couldn\'t find his street',
    'Death has no days off',
    'He was a good cobbler. Became a bad soldier',
    'Shot first. Will have to live with that',
    'The newspaper reported "minor casualties". He was among them',
    'The mud in the trench is warmer than a blanket',
    'Breakfast for one. Again',
    'The sun shone as if nothing had happened',
    'His dog howled for three nights straight',
    'The price of victory is an empty village',
    'HQ wrote us off yesterday morning',
    'Out of water. The well is on their side of the street',
    'We\'re surrounded',
    'Cleaned his rifle so carefully, as if he intended to live forever',
    'The snow turned red and quickly froze',
    'No one wanted to die',
    'Wrote a note. Read it after the battle',
    'Brothers by mass grave',
    'Asked what time it is. The stupidest question when surrounded',
    'The tanks moved lazily, like well-fed beasts',
    'Hunger stopped tormenting him',
    'We sat in the mud waiting for the offensive',
    'At least he didn\'t have to shine his boots anymore',
    'They just forgot about us here',
    'The lieutenant sat on the ground',
    'According to the map, there should be a forest here. Only stumps and corpses',
    'Nothing left to shoot with'
  ],
});

export const NewsLines = Object.freeze({
  ru: [
    'Рынок разрушен. Торговля прекращена.',
    'Урожай не убран. Зернохранилища пусты.',
    'Беженцы достигли побережья. Корабли не принимают.',
    'Госпиталь переполнен. Медикаменты на исходе.',
    'Школы закрыты третью неделю подряд.',
    'Послы отозваны. Переговоры не ведутся.',
    'Мост взорван. Деревня отрезана.',
    'Цены на хлеб выросли втрое.',
    'Комендантский час продлён до рассвета.',
    'Список пропавших — тысяча имён.',
    'Сводка потерь засекречена.',
  ],
  en: [
    'Market destroyed. Trade halted.',
    'The harvest still stands in the fields. Granaries are empty.',
    'Refugees have reached the coast. No ship will take them.',
    'The hospital is overwhelmed. Medical supplies are running out.',
    'Schools have been closed for three weeks straight.',
    'Ambassadors recalled. Talks suspended.',
    'The bridge has been blown. The village is cut off.',
    'Bread prices have tripled.',
    'Curfew extended until dawn.',
    'Missing persons list: a thousand names.',
    'The casualty report has been classified.',
  ],
});

export const EndQuotes = Object.freeze({
  ru: [
    'Победитель в войне — это тот, кто меньше потерял. Но и он потерял.',
    'Солдаты умирают за то, что политики не могут решить за столом переговоров.',
    'Пограничный камень остался на том же месте.',
    'Причина войны всегда кажется ничтожной на фоне её последствий.',
    'Те, кто объявил войну, пережили её.',
    'Через десять лет здесь построят мемориал. Потом снесут при следующей войне.',
  ],
  en: [
    'The victor in war is the one who lost less. But they still lost.',
    'Soldiers die for what politicians could not settle across a negotiating table.',
    'The border stone did not move.',
    'The cause of a war always seems trivial compared to its consequences.',
    'Those who declared the war outlived it.',
    'In ten years they will build a memorial here—then tear it down when the next war comes.',
  ],
});

/** Пороги суммарных потерь для всплывающих сообщений */
export const CasualtyThresholds = Object.freeze({
  ru: {
    100000: 'Это больше, чем население среднего города.',
    500000: 'Полмиллиона. Столько зрителей вмещает двадцать стадионов.',
    1000000: 'Миллион. Некоторые войны в истории унесли меньше.',
  },
  en: {
    100000: 'More than the population of a mid-sized city.',
    500000: 'Half a million. That many people could fill twenty football stadiums.',
    1000000: 'One million dead. Some wars in history claimed fewer lives.',
  },
});
